FROM httpd
RUN apt update
RUN apt upgrade
RUN apt install -y git gprbuild gnat libpng-dev ruby rubygems
RUN gem install cgi zip stringio tempfile tmpdir fileutils
# WORKDIR /tmp
# RUN git clone https://github.com/riccardo-bernardini/espert_uniud.git
# WORKDIR espert_uniud/accumulator
# RUN gprbuild
