FROM fintatarta/espert_uniud:building

WORKDIR /tmp
RUN git clone https://github.com/riccardo-bernardini/espert_uniud.git

WORKDIR espert_uniud
RUN git checkout compatibility

WORKDIR Docker
RUN ./install-apache.sh

CMD ["/usr/local/bin/http-and-worker.sh"]
