#!/usr/bin/bash

function readable_file_or_die
{
    name=$1

    if [ ! -f "$name" ]; then
	echo "'$name' is not a regular file or it does not exist" >&2
	exit 1
    fi

    if [ ! -r "$name" ]; then
	echo "File '$name' is not readable" >&2
	exit 1
    fi
}

function writable_dir_or_die
{
    name=$1

    if [ ! -d "$name" ]; then
	echo "'$name' is not a directory or it does not exist" >&2
	exit 1
    fi

    if [ ! -w "$name" ]; then
	echo "Directory '$name' is not writable" >&2
	exit 1
    fi
}

function to_dv
{
    if [ -n "$runtime_pid" ]; then 
	dv-control -p $port -s "$1"
    fi
}

if [ $# -lt 3 -o $# -gt 4 ]; then
    echo "Usage: $0 input config output-dir [prefix]" >&2
    exit 1
fi

input="$1"
readable_file_or_die "$input"
shift

config="$1"
readable_file_or_die "$config"
shift

output_dir="$1"
writable_dir_or_die "$output_dir"
shift

echo "(($#))"

if [ $# -gt 0 ]; then
    echo "[[[$#,$1]]]"
    prefix="$1"
    shift
else
    prefix="frame"
fi

port=5433

if true ; then
    dv-runtime -p $port &
    runtime_pid=$!

    sleep 5
fi

(while read ; do
     echo "$REPLY" >> /tmp/u.log

     to_dv "$REPLY" 

     if [ $? -ne 0 ]; then
	 echo $?
	 exit 1
     fi
 done)<<EOF
add_module inp dv_converter
add_module acc dv_accumulator
add_module out dv_image_output
set /mainloop/acc/inputs/events/ from inp[events]
set /mainloop/out/inputs/frames/ from acc[frames]
set /mainloop/inp/ logLevel DEBUG
set /mainloop/out/ logLevel DEBUG
set /mainloop/out/ logLevel DEBUG
set /mainloop/inp/ file $input
set /mainloop/out/ directory $output_dir
set /mainloop/out/ imageFilePrefix $prefix
EOF


if true ; then
(while read ; do
     if [ "${REPLY:0:1}" = "#" ]; then
	 continue
     fi
     
     command="set /mainloop/acc/ $REPLY"
     echo "$command"
     to_dv "$command"

     if [ $? -ne 0 ]; then
	 echo $?
	 exit 1
     fi
 done)< $config
fi

(while read ; do
     echo "$REPLY"

     to_dv "$REPLY"

     if [ $? -ne 0 ]; then
	 echo $?
	 exit 1
     fi
 done)<<EOF
set /mainloop/out/ running true
set /mainloop/acc/ running true
set /mainloop/inp/ running true
EOF

to_dv "get /mainloop/out/ isRunning"

if [ -n "$runtime_pid" ]; then
    echo Waiting...
    sleep 5
    
    is_running=`to_dv "get /mainloop/out/ isRunning"`
    echo $is_running
    while [ $is_running = "true" ]; do
	sleep 1
	is_running=`to_dv "get /mainloop/out/ isRunning"`
	echo $is_running
    done

    echo Done

    kill $runtime_pid
    wait $runtime_pid
fi



