#!/usr/bin/bash

input=single-pixel.aedat

for k in 0 1 2 3 4 5 6; do
#for k in 0 ; do
    config="config-$k.txt"
    target="/tmp/target-$k"
#    target=/tmp
    ./dv-run $input $config $target
done
